font_family      CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

include current-theme.conf

hide_window_decorations yes

tab_bar_min_tabs        2
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_align           left

cursor_shape beam

window_padding_width 6

disable_ligatures cursor

enable_audio_bell no
visual_bell_duration 0.3

confirm_os_window_close 0

strip_trailing_spaces smart

mouse_hide_wait 2.0

scrollback_lines 10000

select_by_word_characters @-./_~?&=%+#

map --new-mode resize-mode kitty_mod+r

map --mode resize-mode up    resize_window taller
map --mode resize-mode down  resize_window shorter
map --mode resize-mode right resize_window wider
map --mode resize-mode left  resize_window narrower

map --mode resize-mode esc   pop_keyboard_mode
map --mode resize-mode enter pop_keyboard_mode
